# Generated by Django 5.0.4 on 2024-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_image_field_buyer_address_cart_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_field',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
