# Generated by Django 5.0.4 on 2024-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_field',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
