# Generated by Django 5.0.4 on 2024-05-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_cart_quantity_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
